services:
  jekyll:
    build: .
    container_name: lsf_website
    ports:
      - "4000:4000" # Jekyll web server
      - "35729:35729" # LiveReload port for auto-refresh
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache:
